# Generated by Django 5.2.17 on 2026-08-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_seller_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='brands', to='shop.category', verbose_name='İlgili Kategoriler'),
        ),
    ]
